export const REQUEST_USER_TOKEN = 'REQUEST_USER_TOKEN';
export const RECEIVE_USER_TOKEN = 'RECEIVE_USER_TOKEN';
export const RECEIVE_USER_TOKEN_FAIL = 'RECEIVE_USER_TOKEN_FAIL';
export const VALIDATE_USER_TOKEN = 'VALIDATE_USER_TOKEN';
